### ISSUE TITLE
Help me out with this

### ISSUE THREAD

**Issue by alienMak** [aadiiks/CTF-Writeups#1]
![Screenshot_2021-06-29_23_32_28](https://user-images.githubusercontent.com/54765654/123873308-edcbc700-d953-11eb-82a2-b826429103cc.png)

**Comment by aadiiks** [comment]
Sorry for late reply.
As I can see you are using gobuster for doing a directory search over an IP. But you haven't assigned a wordlist file containing the directory name to start the scan.
In your command where you are writing:
$ gobuster dir -u http://164.52.211.11.8006/ -w /usr/share/wordlists

At last of this command you need to select a txt file for searching as wordlists is a whole directory.
Press tab after writing the command and you will be provided with all the txt files present and choose your preferred one.
Like this:
$ gobuster dir -u http://164.52.211.11.8006/ -w /usr/share/wordlists/common.txt

**Comment by alienMak** [comment]
I tried that command before but tab didn't auto complete it and showed the
same error.
My deadline is tomorrow. I don't think I will be able to submit

**Comment by aadiiks** [comment]
Have you downloaded the wordlists directory. Command for doing so is apt-get(older debian) or apt(newer debian):
$ sudo apt install wordlists

And then proceed.

**Comment by aadiiks** [comment]
If the issue persists contact me on discord with id - 0xA4di1#1021

or join the server with address - https://discord.gg/ZesudSzQ

I will try my best to solve the issue.

**Comment by aadiiks** [comment]
I did a quick search on the IP that you were trying. Found a page named **robots.html** which redirects to **ctf.html** with some sort of encrypted code.
I also came to know it is a part of ongoing CTF competition so won't be able to disclose the flag now.

**Comment by aadiiks** [comment]
![gobuster](https://user-images.githubusercontent.com/68190936/124010821-f5937600-d9fc-11eb-9aff-02dfa9961f4c.PNG)

And as you can see the working of gobuster here with the same command you are trying. Hope this helps.
